
<?=$this->msg?>
<hr/>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et saepe officium est sapientis desciscere a vita, cum sit beatissimus, si id oportune facere possit, quod est convenienter naturae. Omnes enim iucundum motum, quo sensus hilaretur. Ita similis erit ei finis boni, atque antea fuerat, neque idem tamen; Atque hoc loco similitudines eas, quibus illi uti solent, dissimillimas proferebas. Duo Reges: constructio interrete. Id autem eius modi est, ut additum ad virtutem auctoritatem videatur habiturum et expleturum cumulate vitam beatam, de quo omnis haec quaestio est. </p>

<p>Iam quae corporis sunt, ea nec auctoritatem cum animi partibus, comparandam et cognitionem habent faciliorem. Addo etiam illud, multa iam mihi dare signa puerum et pudoris et ingenii, sed aetatem vides. Sed audiamus ipsum: Compensabatur, inquit, tamen cum his omnibus animi laetitia, quam capiebam memoria rationum inventorumque nostrorum. Vides igitur te aut ea sumere, quae non concedantur, aut ea, quae etiam concessa te nihil iuvent. Itaque et manendi in vita et migrandi ratio omnis iis rebus, quas supra dixi, metienda. Atqui pugnantibus et contrariis studiis consiliisque semper utens nihil quieti videre, nihil tranquilli potest. Quid enim de amicitia statueris utilitatis causa expetenda vides. Iis igitur est difficilius satis facere, qui se Latina scripta dicunt contemnere. Atque haec ita iustitiae propria sunt, ut sint virtutum reliquarum communia. Nobis enim ista quaesita, a nobis descripta, notata, praecepta sunt, omniumque rerum publicarum reetionis genera, status, mutationes, leges etiam et instituta ac mores civitatum perscripsimus. Hoc ille tuus non vult omnibusque ex rebus voluptatem quasi mercedem exigit. Sin dicit obscurari quaedam nec apparere, quia valde parva sint, nos quoque concedimus; </p>

<p>Idque testamento cavebit is, qui nobis quasi oraculum ediderit nihil post mortem ad nos pertinere? Nec enim, dum metuit, iustus est, et certe, si metuere destiterit, non erit; Sit enim idem caecus, debilis. Quodcumque in mentem incideret, et quodcumque tamquam occurreret. Cum autem in quo sapienter dicimus, id a primo rectissime dicitur. Nec vero pietas adversus deos nec quanta iis gratia debeatur sine explicatione naturae intellegi potest. Ecce aliud simile dissimile. Te enim iudicem aequum puto, modo quae dicat ille bene noris. Minime vero istorum quidem, inquit. Cuius etiam illi hortuli propinqui non memoriam solum mihi afferunt, sed ipsum videntur in conspectu meo ponere. Itaque nostrum est-quod nostrum dico, artis est-ad ea principia, quae accepimus. </p>

<p>Negabat igitur ullam esse artem, quae ipsa a se proficisceretur; Ita multa dicunt, quae vix intellegam. </p>

<p>Ergo in iis adolescentibus bonam spem esse dicemus et magnam indolem, quos suis commodis inservituros et quicquid ipsis expediat facturos arbitrabimur? Atque ut a corpore ordiar, videsne ut, si quae in membris prava aut debilitata aut inminuta sint, occultent homines? Claudii libidini, qui tum erat summo ne imperio, dederetur. Primum non saepe, deinde quae est ista relaxatio, cum et praeteriti doloris memoria recens est et futuri atque inpendentis torquet timor? Atque omnia quidem scire, cuiuscumque modi sint, cupere curiosorum, duci vero maiorum rerum contemplatione ad cupiditatem scientiae summorum virorum est putandum. Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. Quicquid porro animo cernimus, id omne oritur a sensibus; Putabam equidem satis, inquit, me dixisse. Et si turpitudinem fugimus in statu et motu corporis, quid est cur pulchritudinem non sequamur? Nam haec ipsa mihi erunt in promptu, quae modo audivi, nec ante aggrediar, quam te ab istis, quos dicis, instructum videro. </p>

<p>Vide, ne magis, inquam, tuum fuerit, cum re idem tibi, quod mihi, videretur, non nova te rebus nomina inponere. Illorum vero ista ipsa quam exilia de virtutis vi! Quam tantam volunt esse, ut beatum per se efficere possit. Non dolere, inquam, istud quam vim habeat postea videro; Intrandum est igitur in rerum naturam et penitus quid ea postulet pervidendum; Scaevola tribunus plebis ferret ad plebem vellentne de ea re quaeri. At quanta conantur! Mundum hunc omnem oppidum esse nostrum! Incendi igitur eos, qui audiunt, vides. Ex quo illud efficitur, qui bene cenent omnis libenter cenare, qui libenter, non continuo bene. Nihil opus est exemplis hoc facere longius. Nec enim, omnes avaritias si aeque avaritias esse dixerimus, sequetur ut etiam aequas esse dicamus. Nec tamen ullo modo summum pecudis bonum et hominis idem mihi videri potest. Chrysippus autem exponens differentias animantium ait alias earum corpore excellere, alias autem animo, non nullas valere utraque re; </p>

<p>Decius, princeps in ea familia consulatus, cum se devoverat et equo admisso in mediam aciem Latinorum irruebat, aliquid de voluptatibus suis cogitabat? Nam Pyrrho, Aristo, Erillus iam diu abiecti. Quo studio cum satiari non possint, omnium ceterarum rerum obliti níhil abiectum, nihil humile cogitant; Ut placet, inquit, etsi enim illud erat aptius, aequum cuique concedere. Nam constitui virtus nullo modo potesti nisi ea, quae sunt prima naturae, ut ad summam pertinentia tenebit. Hoc enim constituto in philosophia constituta sunt omnia. Utrum igitur percurri omnem Epicuri disciplinam placet an de una voluptate quaeri, de qua omne certamen est? </p>

<p>Quid autem habent admirationis, cum prope accesseris? Etsi ea quidem, quae adhuc dixisti, quamvis ad aetatem recte isto modo dicerentur. Hoc non est positum in nostra actione. Zenonis est, inquam, hoc Stoici. Quae est quaerendi ac disserendi, quae logikh dicitur, iste vester plane, ut mihi quidem videtur, inermis ac nudus est. Atque ita re simpliciter primo collocata reliqua subtilius persequentes corporis bona facilem quandam rationem habere censebant; </p>

<p>Dolere malum est: in crucem qui agitur, beatus esse non potest. Quis est enim, qui hoc cadere in sapientem dicere audeat, ut, si fieri possit, virtutem in perpetuum abiciat, ut dolore omni liberetur? Nihil est enim, de quo aliter tu sentias atque ego, modo commutatis verbis ipsas res conferamus. Facit igitur Lucius noster prudenter, qui audire de summo bono potissimum velit; Polemoni et iam ante Aristoteli ea prima visa sunt, quae paulo ante dixi. Sed tamen intellego quid velit. Sin te auctoritas commovebat, nobisne omnibus et Platoni ipsi nescio quem illum anteponebas? Quid ergo attinet dicere: Nihil haberem, quod reprehenderem, si finitas cupiditates haberent? Bonum liberi: misera orbitas. Obsecro, inquit, Torquate, haec dicit Epicurus? </p>

<p>Non igitur potestis voluptate omnia dirigentes aut tueri aut retinere virtutem. Neque enim civitas in seditione beata esse potest nec in discordia dominorum domus; Scripsit enim et multis saepe verbis et breviter arteque in eo libro, quem modo nominavi, mortem nihil ad nos pertinere. Ut necesse sit omnium rerum, quae natura vigeant, similem esse finem, non eundem. Quodsi vultum tibi, si incessum fingeres, quo gravior viderere, non esses tui similis; Esse enim quam vellet iniquus iustus poterat inpune. Tum Triarius: Posthac quidem, inquit, audacius. Graecis hoc modicum est: Leonidas, Epaminondas, tres aliqui aut quattuor; </p>

